spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/1843080373/spring-cloud/
          username: 1843080373
          password: 18076575691abcd
          search-paths: /**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
server:
  port: 8888
  