spring:
  application:
    name: zk-client
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
        enabled: true
        instance-id: 1
        root: /shenniu
        instance-host: 127.0.0.1
server:
  port: 9999
  