server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/ 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    
spring:
  cloud:
    config:
      server: 
        native:
          search-locations: file:E:/GitHub/spring-cloud/zmph-shop-parent/properties # classpath:properties/搜索src/main/resource 下的properties文件夹下的文件
    #自动刷新
    bus:
      refresh:
        enabled: true
  application:
    name: zmph-config-server
  profiles:
    active: native  # 配置使用本地储存
    
#本地环境无需配置，只需启动mq
rabbitmq: 
  host: localhost
  port: 5672
  username: guest
  password: guest
 
#进行暴露服务
management:
  endpoints:
    web:
      exposure:
        include: "*"