server:
  port: 7602
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:7000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddr}:${server.port}   
