server:
  port: 7900
  
spring:
  application: 
    name: zmph-api-gateway
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  #jackson相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #时区必须要设置
    time-zone: GMT+8
    #ALWAYS的意思是即时属性为null，仍然也会输出这个key
    default-property-inclusion: ALWAYS
    serialization:
      indent-output: true

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG
    
zuul:
  routes:
    zmph-shop-usersrv: /api-user-prefix/**
    zmph-shop-productsrv: /api-product-prefix/**
    
# 描述信息
info:
  blog-url: http://blog.battcn.com
  author: Levin
  version: '@project.version@'
  env: '@spring.profiles.active@'
  app:
    name: ${spring.application.name}-${server.port}
  company:
    name: www.cloud.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
# 加载所有的端点/默认只加载了 info / health
management:
  endpoints:
    web: 
      exposure: 
        include: "*"
    health:
      show-details: always
# 可以关闭制定的端点
    shutdown:
      enabled: false